#!/bin/bash
echo ">> Creating folder"
mkdir $(pwd)/$1;
cd $(pwd)/$1;

echo ">> Setting up YARN...";
yarn init --yes;

echo ">> Running YARN install...";
yarn add react react-dom @babel/polyfill;
yarn add -D parcel-bundler @babel/core @babel/preset-env @babel/preset-react @babel/plugin-proposal-class-properties;

echo ">> Setting up initial files...";
# .babelrc
echo '{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": ["@babel/plugin-proposal-class-properties"]
}
' >> .babelrc;

# Setup directories
mkdir src;

# index.html
echo '<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no"
    />
    <title>React Parcel Starter</title>
  </head>
  <body>
    <div id="root"></div>
    <script src="index.js"></script>
  </body>
</html>
' >> src/index.html;

# src/index.js
echo "import React from \"react\";
import ReactDOM from \"react-dom\";
import App from \"./App.js\";
import \"@babel/polyfill\";

ReactDOM.render(<App />, document.getElementById(\"root\"));" >> src/index.js;

# src/App.js
echo "import React from \"react\";
const App = () => {
  return (
    <div>
      <h1>React Parcel Starter</h1>
    </div>
  );
};
export default App;" >> src/App.js;

sed -i '$s/}/,  "scripts": {\n    "dev": "parcel \.\/src\/index.html",\n    "build": "parcel build .\/src\/index.html"\n  }\n}/' package.json;
jq . package.json > package-new.json;
rm -rf package.json;
mv package-new.json package.json;

echo ">> Setting up Git..."
git init;

# .gitignore
echo "/node_modules
/.parcel-cache
/.pnp
.pnp.js

/coverage

/build

.DS_Store
.env.local
.env.development.local
.env.test.local
.env.production.local

npm-debug.log*
yarn-debug.log*
yarn-error.log*" >> .gitignore;
